#!/usr/bin/env bash
# a script that configures a  my new Ubuntu 
# server machine to respect the requirements

sudo su
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
