#!/usr/bin/env bash

# to start mysql

sudo mysql -u root -p2849

# to create user
CREATE USER 'replica_user'@'%' IDENTIFIED WITH mysql_native_password BY '';

# to grant privilages
GRANT ALL PRIVILEGES ON *.* TO 'replica_user'@'%' WITH GRANT OPTION;

# to see the users in mysql
SELECT user,host FROM mysql.user;

# to see privilages
SHOW GRANTS FOR replica_user;
