#!/usr/bin/env bash
# Bash script that displays/prints fizz when i%3==0
#prints buzz when i%5==0
#prints fizzbuzz when i%3==0 and i%5==0
i=1
while ((i <= 100)); do
	if ((i % 5 == 0 && i % 3 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
