#!/usr/bin/env bash
# FizzBuzz Bash Script
# Description: Prints numbers from 1 to 100,
#replacing multiples of 3 with "Fizz",
# multiples of 5 with "Buzz", and multiples of both 3 and 5 with "FizzBuzz".
i=1
while ((i <= 100)); do
	if ((i % 5 == 0 && i % 3 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
