#!/usr/bin/env bash
# Displays the content of the file /etc/passwd
#script should only display:
#username
#user id
#Home directory path for the user
while IFS=: read -r file; do
	echo "$file" | cut -d ":" -f 1,3,6
done </etc/passwd
