#!/usr/bin/env bash
# Bash script that displays the content of the file
# /etc/passwd, using the while loop + IFS.

IFS=":"
while read -r Username Password UserID GID GECOS Home Command; do
	echo "The user $Username is part of the $GID gang, lives in $Home and rides $Command. $UserID's place is protected by the passcode $Password, more info about the user here: $GECOS"
done </etc/passwd
