#!/usr/bin/env bash
# print "Best School" 10 times
hour=0
while ((hour<13)); do
	min=1
	((hour++))
	while ((min<60)); do
		echo $min
		((min++))
	done
	if ((hour==13)); then
		break
	fi
	echo "Hour: "$hour

done