#!/usr/bin/env bash
# Bash script that displays/prints content
school_file=school
if [ -e "$school_file" ] ; then
	echo "school file exists"
	if [ ! -s "$school_file" ]; then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f "$school_file" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi