#!/usr/bin/env bash
# a Bash script that creates an RSA key pair.
# ssh-keygen [-t dsa | ecdsa | ecdsa-sk | ed25519 | ed25519-sk | rsa]
# ssh-keygen [-b bits] [-f output_keyfile] [-N new_passphrase]

ssh-keygen -t rsa -f school -b 4096 -N "betty"
